### ISSUE TITLE
Feature Request : Multi Mission

### ISSUE THREAD

**Issue by benda95280** [pjz9n-pm-pl/Mission#10]
Dear,

Is it possible to have multi-mission ?

Something like :
/mission edit "NameOfMission"
/mission show "NameOfMission"
/mission list

Goal : 
Be able to call different mission type with slapper

Thanks for that awsome plugin ;)

**Comment by PJZ9n** [comment]
We added that feature in [1.1.0 Release](https://github.com/pjz9n-pm-pl/Mission/releases/tag/1.1.0).

The following features have been added to the command:
`/mission <name, ID, and Short ID>` - Show the specified mission detail
`/mission edit <name, ID, and Short ID>` - Edit the specified mission

You can refer to the README for more information.

Thanks for your request!

**Comment by benda95280** [comment]
From what i've read, if '/mission' is used without argument, all mission are shown ?
If i create 50 Missions, all will be shown to the player ?

I ask because if going to create mission per world/slapper, they will be able to have all of them.

Thanks for the fast Update ! 👍

**Comment by PJZ9n** [comment]
Yes, if used with no arguments, a list of all missions will be displayed.

**Comment by benda95280** [comment]
Could it be possible to prevent it ?

**Comment by PJZ9n** [comment]
In the Future release plan, it will be possible to set a group for each mission, for example, execute `/mission list [name-of-group]` will display a list of missions belonging to that group.
