### ISSUE TITLE
add reward with commands

### ISSUE THREAD

**Issue by ItzFel** [pjz9n-pm-pl/Mission#11]

**Comment by PJZ9n** [comment]
What does that mean? Please be specific.

**Comment by jadperr** [comment]
> What does that mean? Please be specific.

reward with command like:
givemoney {player} 1000
key {player} common 1
and more plugin command..

I also request this feature :D

**Comment by Adam1609** [comment]
This reward with command can be used with Mineflow. Please read the README to learn how to add command

**Comment by PJZ9n** [comment]
It seems possible with Mineflow, so close it.
