### ISSUE TITLE
Mineflow does not appear the right translation

### ISSUE THREAD

**Issue by Adam1609** [pjz9n-pm-pl/Mission#13]
![Capture5](https://user-images.githubusercontent.com/16860075/101272930-681fd880-37c3-11eb-825f-9a37d51c88f7.PNG)

This show in the Mineflow recipe menu, is this cause by Mineflow or the language of your plugin?

**Comment by PJZ9n** [comment]
Did you use the latest version of Mineflow?

**Comment by Adam1609** [comment]
Yes I use latest version

**Comment by Adam1609** [comment]
Closed this issue, apparently I didn't have the right version of your plugin

**Comment by PJZ9n** [comment]
I have identified the cause and fixed the related bug!
