### ISSUE TITLE
Double message shown in console

### ISSUE THREAD

**Issue by Adam1609** [pjz9n-pm-pl/Mission#14]
Executing a Mineflow reward will cause double message shown in console. I have posted an issue on Mineflow and they said that they can't reproduce the issue.

https://github.com/aieuo/Mineflow/issues/30

**Comment by PJZ9n** [comment]
Is there more than one Mineflow reward in one mission?

**Comment by Adam1609** [comment]
Oh yes, there IS more than one

**Comment by PJZ9n** [comment]
If you look carefully [here](https://github.com/pjz9n-pm-pl/Mission#examples), you can see that there is one `Mineflow reward` and the second is `Nothing`.
I'm sorry this is due to the bad architecture of this plugin.

**Comment by Adam1609** [comment]
Oh noticed! I didn't pay attention to that.

**Comment by Adam1609** [comment]
I will close this issue for now, if there is any error, I will inform as possible
