### ISSUE TITLE
sugegst

### ISSUE THREAD

**Issue by BLAST1718** [pjz9n-pm-pl/Mission#15]
make a thing where if u create a mission u can create somethibg like it requires to get the certain blocks like it requires diamond block it will not work with other block just diamond block

**Comment by PJZ9n** [comment]
Can you use Mineflow to solve this problem?
https://github.com/pjz9n-pm-pl/Mission#use-the-recipe-as-a-steptrigger

**Comment by BLAST1718** [comment]
Can u add an scorehud addon?

**Comment by Adam1609** [comment]
@BLAST1718 if you want to create anything in the mission section, can you please use Mineflow to create custom mission.

**Comment by BLAST1718** [comment]
how i clearly dont understand the tutorial

**Comment by PJZ9n** [comment]
To do that, you need to use Mineflow.
There are no plans to reinvent the wheel with this plugin.

For the ScoreHUD addon, we have opened a new issue.
https://github.com/pjz9n-pm-pl/Mission/issues/17

Therefore, I close the issue.
