### ISSUE TITLE
[Suggestion] Adding new event as introduced in the latest version of Mineflow

### ISSUE THREAD

**Issue by Adam1609** [pjz9n-pm-pl/Mission#16]
As Mineflow was updated in the previous version, this adding new event such as:

- When player or entity dead

Can you please add this to the Event section?

**Comment by PJZ9n** [comment]
That is, do you want to add it to the event list in Steptrigger->Event?

**Comment by Adam1609** [comment]
Yes, that is what I am suggest.

**Comment by PJZ9n** [comment]
I tried and found that there were technical barriers.
This issue has been added to the milestones for the next minor version.

I found that Mineflow could be used instead.

**Comment by Adam1609** [comment]
In a meantime, can I add a support to another language?

**Comment by PJZ9n** [comment]
Sorry for the delay in confirming the message.
this page explains how to do it.
https://github.com/pjz9n-pm-pl/Mission/wiki/How-to-support-new-languages

**Comment by Adam1609** [comment]
Will close this issue due to the fact that i don't have free time to contribute
