### ISSUE TITLE
Scorehud addon [suggestion]

### ISSUE THREAD

**Issue by BLAST1718** [pjz9n-pm-pl/Mission#18]
{mission} = for what ongoing mission ur doing

{next_mission} = ur next mission

{mission_progress} = progress on the mission (like 1/5)

**Comment by PJZ9n** [comment]
Since there can be multiple missions in progress, is there a reasonable way to specify them?

**Comment by BLAST1718** [comment]
wdym?

**Comment by BLAST1718** [comment]
> Since there can be multiple missions in progress, is there a reasonable way to specify them?

maybe like is it possible to make it so u can only have 1 mission ongoing at once?

**Comment by BLAST1718** [comment]
?

**Comment by PJZ9n** [comment]
With the version 1.6.0 update, the ScoreHUD add-on is now supported!
