### ISSUE TITLE
Triggers continue to remain after uninstall

### ISSUE THREAD

**Issue by fuyutsuki** [pjz9n-pm-pl/Mission#25]
**Describe the bug**
Triggers will continue to remain after uninstall this plugin, and clicking on them will block the player

**To Reproduce**
1. Install this with Mineflow
2. Uninstall only this
3. Type `/mf`
4. Click Mission trigger

**Expected behavior**
Shouldn't show trigger

**Screenshots**
![image](https://user-images.githubusercontent.com/16377174/112406517-ad0e5180-8d57-11eb-97c7-df8fa54df0cf.png)

**Environments (please complete the following information):**

- PMMP version: 3.18.0
- PHP version: 8.0.3
- Plugin version: none
- OS: Win10 Pro
- Mineflow version: 1.3.1

**Additional context**
MineflowのEventTriggerListでMineflow側のplugin_dataに保存されてしまうのが原因ですが、これを修正するにはMineflow側の変更が必要になるかもしれません。

**Comment by aieuo** [comment]
2.0の方ですがMineflow側を変更しました

**Comment by fuyutsuki** [comment]
2.0に対応すればokですね、PJさん頑張れ！

**Comment by PJZ9n** [comment]
報告ありがとうございます、対応頑張ります！
