### ISSUE TITLE
incompatibility with MineFlow. EventTriggerList is now EventManager

### ISSUE THREAD

**Issue by DarcZera** [pjz9n-pm-pl/Mission#29]
MineFlow changed the class! is no longer an EventTriggerList, it has become an EventManager

< 13.04 01:18:07 [Server] Server thread/CRITICAL Error: "Class 'aieuo\mineflow\trigger\event\EventTriggerList' not found" (EXCEPTION) in "plugins/Mission.phar/src/pjz9n/mission/Main" at line 99
13.04 01:18:07 [Server] Server thread/CRITICAL #0 pmsrc/src/pocketmine/plugin/PluginManager(182): pjz9n\mission\Main->onLoad()
13.04 01:18:07 [Server] Server thread/CRITICAL #1 pmsrc/src/pocketmine/plugin/PluginManager(346): pocketmine\plugin\PluginManager->loadPlugin(string[65] /plugins/Mission.phar, array[2])
13.04 01:18:07 [Server] Server thread/CRITICAL #2 pmsrc/src/pocketmine/Server(1529): pocketmine\plugin\PluginManager->loadPlugins(string[53] /plugins/)
13.04 01:18:07 [Server] Server thread/CRITICAL #3 pmsrc/src/pocketmine/PocketMine(291): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[45] /, string[53] /plugins/)
13.04 01:18:07 [Server] Server thread/CRITICAL #4 pmsrc/src/pocketmine/PocketMine(321): pocketmine\server()
13.04 01:18:07 [Server] Server thread/CRITICAL #5 pmsrc(11): require(string[81] phar:///jar/1.16.220.phar/src/pocketmine/PocketMine.ph)
13.04 01:18:07 [Server] Server thread/CRITICAL Could not load plugin 'Mission' >

**Comment by PJZ9n** [comment]
Mineflow has released a major update (2.x.x). However, this plugin currently only supports 1.x.x.
Therefore, we are currently making the Mission plugin compatible with Mineflow 2.x.x.

**Comment by PJZ9n** [comment]
This has been fixed in the [1.6.3](https://github.com/pjz9n-pm-pl/Mission/releases/tag/1.6.3) release and will close this issue.
