### ISSUE TITLE
Does nothing

### ISSUE THREAD

**Issue by DarcZera** [pjz9n-pm-pl/Mission#32]
I installed the 1.6.3 plugin on the server and it just doesn't start, it does absolutely nothing. as if it were just another blank file
nothing appears on the console saying it is activating the plugin. when I enter the server and type /plugins, it does not appear

Pocketmine 
Version: 1.16.220
API : 3.19.0
Mcpe-protocol: 431
Download from: GitHub

**Comment by PJZ9n** [comment]
I've tried it with GitHub Release 1.6.3 and it seems to work fine so the file may have been corrupted during the download.
Try downloading the .phar file from Poggit Release.
https://poggit.pmmp.io/p/Mission/1.6.3

**Comment by PJZ9n** [comment]
I close this issue as it has not been posted recently.
If the problem persists, you can reopen it.
