### ISSUE TITLE
Everyone recieve the mission can complete without steptrigger"ing"

### ISSUE THREAD

**Issue by Adam1609** [pjz9n-pm-pl/Mission#6]
When creating a BlockBreakEvent steptriggering, recieving a mission would automatically be completed without breaking, due to other players do the breaking. Is this a bug or intend?

**Comment by PJZ9n** [comment]
This bug has been fixed in [1.0.3 Release](https://github.com/pjz9n-pm-pl/Mission/releases/tag/1.0.3).
Thank you.
